version: '3.1'

services:
  security_app:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: security_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
